<?php
/**
 * OmnimessageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Messente API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Messente\Api;

use PHPUnit\Framework\TestCase;

/**
 * OmnimessageTest Class Doc Comment
 *
 * @category    Class
 * @description Omnimessage
 * @package     Messente\Api
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OmnimessageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Omnimessage"
     */
    public function testOmnimessage()
    {
    }

    /**
     * Test attribute "to"
     */
    public function testPropertyTo()
    {
    }

    /**
     * Test attribute "messages"
     */
    public function testPropertyMessages()
    {
    }

    /**
     * Test attribute "dlrUrl"
     */
    public function testPropertyDlrUrl()
    {
    }

    /**
     * Test attribute "timeToSend"
     */
    public function testPropertyTimeToSend()
    {
    }
}
