<?php
/**
 * OmnimessageApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Messente\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Messente API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: messente@messente.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0-beta2
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Messente\Api;

use \Messente\Api\Configuration;
use \Messente\Api\ApiException;
use \Messente\Api\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OmnimessageApiTest Class Doc Comment
 *
 * @category Class
 * @package  Messente\Api
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OmnimessageApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for cancelScheduledMessage
     *
     * Cancels a scheduled Omnimessage..
     *
     */
    public function testCancelScheduledMessage()
    {
    }

    /**
     * Test case for sendOmnimessage
     *
     * Sends an Omnimessage..
     *
     */
    public function testSendOmnimessage()
    {
    }
}
