name: Publish package to Packagist
on:
  push:
    tags:
      - "*"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish Artifact
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: curl -XPOST -H 'content-type:application/json' "https://packagist.org/api/update-package?username=messente.developers&apiToken=${API_TOKEN}" -d '{"repository":{"url":"https://packagist.org/packages/messente/messente-api-php"}}'

